### PR TITLE
Update stackMachine.hpp

### PR DESCRIPTION
**Pull request by MatthiasHeinz**
Fixed compiler errors related to z3 library.

### CODE REVIEW

**Review by laluka — APPROVED** [review]
Tested with latest z3, fixes the issue

**Comment by leetonidas** [comment]
Which OS are you using and have you installed z3 using the packet manager or from git?

**Comment by laluka** [comment]
ubuntu 18 in a docker (destroyed by now), was from the repop

**Comment by leetonidas** [comment]
Please note that ubuntu 18 provides z3 version [4.4.1](https://packages.ubuntu.com/search?keywords=z3) (checked: 2019-05-06), that was published back in [2015](https://github.com/Z3Prover/z3/releases/tag/z3-4.4.1). z3 introduced api breaking changes meanwhile. Demov has been brought inline with the new api in commit 99d8389c4f844a46d690f1e1edc8732d28df6690. I searched for a little while and did not found a way to make the build compatible with both z3 api versions at the same time, due to a lack of version number defines in z3.

Edit: Link was broken

**Pull request closed without merging**
